### ISSUE TITLE
Add Transport Type JsonRpc

### ISSUE THREAD

**Issue by blaggacao** [fanout/pollymer#13]
Hi I don't really know a lot about javascript (I'm a real noob in it!) and at the risk of making a bullshit request, but it would be great if you could add support JsonRpc (and maybe XmlRpc) transport type, so I can use pollymer in my project.

The projects framework uses its own implementation which I copy here... Maybe it is not too difficult to transform that into the concepts and coding style uses here in pollymer?

Maybe you can even give me hints on what cleanup needs to be done, so I can pull together prepare some basic work in a PR?

```javascript

function genericJsonRpc (fct_name, params, fct) {
    var data = {
        jsonrpc: "2.0",
        method: fct_name,
        params: params,
        id: Math.floor(Math.random() * 1000 * 1000 * 1000)
    };
    var xhr = fct(data);
    var result = xhr.pipe(function(result) {
        core.bus.trigger('rpc:result', data, result);
        if (result.error !== undefined) {
            if (result.error.data.arguments[0] !== "bus.Bus not available in test mode") {
                console.error("Server application error", JSON.stringify(result.error));
            }
            return $.Deferred().reject("server", result.error);
        } else {
            return result.result;
        }
    }, function() {
        //console.error("JsonRPC communication error", _.toArray(arguments));
        var def = $.Deferred();
        return def.reject.apply(def, ["communication"].concat(_.toArray(arguments)));
    });
    // FIXME: jsonp?
    result.abort = function () { if (xhr.abort) xhr.abort(); };
    return result;
}

function jsonRpc(url, fct_name, params, settings) {
    return genericJsonRpc(fct_name, params, function(data) {
        return $.ajax(url, _.extend({}, settings, {
            url: url,
            dataType: 'json',
            type: 'POST',
            data: JSON.stringify(data, time.date_to_utc),
            contentType: 'application/json'
        }));
    });
}
```
/cc @GabbasovDinar fyi

**Comment by jkarneges** [comment]
Pollymer is designed to work with any HTTP API. The request body can contain any content type. By default the response body is parsed as JSON but you can disable this by setting `rawResponse`. So you should be able to make requests to a JSON-RPC service without having to modify Pollymer.

**Comment by blaggacao** [comment]
@jkarneges I have done the integration in pollymer (and learned some bits about javascript). Would such development be eligible for a PR and review?

**Comment by jkarneges** [comment]
Hi @blaggacao , I appreciate the offer but I'm not sure I understand why Pollymer should need such content awareness. The library is intended to be generic.

**Comment by blaggacao** [comment]
My argument might not be convincing: So that it get's abstracted away out of the main code of my application... :smile:
