### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by Parakleta** [fanout/pollymer#5]
Can you please publish this package to NPM so that I can use it with webpack.  I've hacked up a custom version that works for now, but it would be nice to have an official distribution.

**Comment by Parakleta** [comment]
As a work-around I am using Parakleta/pollymer@084e085f02f9cb5772cda9f46b734ebe66750670.

I don't know anything about `jspm` and how it interacts with `npm`, but with those changes I was able to run `npm install && npm pack` and have a tarball I can then point other projects at.

**Comment by harmony7** [comment]
I've published to npm https://www.npmjs.com/package/pollymer
Unfortunately I've not had the time make sure it all works under the various package managers / bundlers / etc (jspm/webpack/browserify/etc), but the browser build does work for me at the moment.

Going to close, but please feel free to comment if you experience issues.
