### ISSUE TITLE
Avoid coopting default console behavior

### ISSUE THREAD

**Issue by thomp** [fanout/pollymer#7]
If pollymer is introduced into existing code which relies on console.xxx(...) calls, that console output is lost. Unless one is already on "planet pollymer", it seems likely the typical user will find it a bit disconcerting to have any diagnostic console material disappear from the console when pollymer is first introduced into the code.

Perhaps make it 'minimal-effort' to change the behavior by with something configurable along the lines of a `cooopt_console_p` flag? Or perhaps just avoid having the `consoleInfo` and `consoleError` calls active in the distributed code (e.g., using a modified version of uglify's "drop_console" orr something as simple as #6)?

**Comment by harmony7** [comment]
Logging behavior has been updated, please see README.
I feel the new behavior allows flexibility and also does not disrupt existing things.
If you feel like we should discuss this more, feel free to comment.  Closing for now.
